name: gsl_dart
description: Dart interface to the GNU Scientific Library.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
   ffi: ^1.2.0-dev.0
   path: ^1.8.1

dev_dependencies:
  ffigen: ^4.1.3
  lints: ^1.0.0
  test: ^1.16.0

ffigen:
  output: 'lib/src/gsl_generated_bindings.dart'
  llvm-path:
    - '/usr/lib/llvm-12'
  name: 'Gsl'
  description: 'Dart bindings to GSL'
  headers:
    entry-points:
      - 'third_party/*.h'
