name: gsl_dart
description: Dart interface to the GNU Scientific Library.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
   ffi: ^2.1.0
   path: ^1.8.1

dev_dependencies:
  ffigen: ^10.0.0
  lints: ^3.0.0
  test: ^1.24.0

ffigen:
  output: 'lib/src/gsl_generated_bindings.dart'
  llvm-path:
    - '/usr/lib/llvm-14'
  name: 'Gsl'
  description: 'Dart bindings to GSL'
  headers:
    entry-points:
      - 'third_party/*.h'
